# Generated by Django 3.1.5 on 2021-01-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='google_id',
            field=models.CharField(default='saas', max_length=100),
            preserve_default=False,
        ),
    ]
