# Generated by Django 3.1.5 on 2021-01-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210111_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
