# Generated by Django 3.1.5 on 2021-01-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210112_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
